# Generated by Django 5.1.1 on 2024-09-20 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bookmark_article_id_alter_bookmark_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='image_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
